---
seed: 1984

num_workers: 4
experiment_name: "2021-07-09"

train_datasets:
  - celeba

val_datasets:
  - celeba

model:
  type: segmentation_models_pytorch.Unet
  encoder_name: timm-efficientnet-b3
  classes: 11
  encoder_weights: noisy-student

trainer:
  type: pytorch_lightning.Trainer
#  early_stop_callback: False
  gpus: 4
#  amp_level: O1
  max_epochs: 30
  distributed_backend: ddp
  progress_bar_refresh_rate: 1
  benchmark: True
  precision: 16
  gradient_clip_val: 5.0
  num_sanity_val_steps: 2
  sync_batchnorm: True


scheduler:
  type: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  T_0: 10
  T_mult: 2

train_parameters:
  batch_size: 32
#  epoch_length: 110000 # almost equal to the train sets: coco + vistas + matting + pascal voc

checkpoint_callback:
  type: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: "2021-07-09"
  monitor: val_loss
  verbose: True
  mode: min
  save_top_k: -1

val_parameters:
  batch_size: 16

optimizer:
  type: adamp.AdamP
  lr: 0.0001


train_aug:
  transform:
    __class_fullname__: albumentations.core.composition.Compose
    bbox_params: null
    keypoint_params: null
    p: 1
    transforms:
      - __class_fullname__: albumentations.augmentations.transforms.PadIfNeeded
        always_apply: False
        min_height: 1024
        min_width: 1024
        border_mode: 0 # cv2.BORDER_CONSTANT
        value: 0
        mask_value: 0
        p: 1
      - __class_fullname__: albumentations.augmentations.geometric.rotate.Rotate
        always_apply: False
        limit: 10
        p: 0.2
      - __class_fullname__: albumentations.augmentations.geometric.resize.RandomScale
        always_apply: False
        scale_limit: 0.2
        p: 0.2
      - __class_fullname__: albumentations.augmentations.transforms.CropNonEmptyMaskIfExists
        always_apply: False
        height: 640
        width: 640
        ignore_values: [10, 9, 8, 7, 6, 5, 4, 2, 1]
        p: 1
      - __class_fullname__: albumentations.augmentations.transforms.HorizontalFlip
        always_apply: False
        p: 0.5
      - __class_fullname__: albumentations.core.composition.OneOf
        p: 0.15
        transforms:
            - __class_fullname__: albumentations.augmentations.transforms.ToGray
            - __class_fullname__: albumentations.augmentations.transforms.CLAHE
            - __class_fullname__: albumentations.augmentations.transforms.ToSepia
            - __class_fullname__: albumentations.augmentations.transforms.ColorJitter

degradation_aug:
  transform:
    __class_fullname__: albumentations.core.composition.Compose
    bbox_params: null
    keypoint_params: null
    p: 1
    transforms:
      - __class_fullname__: albumentations.core.composition.OneOf
        p: 0.5
        transforms:
            - __class_fullname__: albumentations.augmentations.transforms.GaussianBlur
              blur_limit: [3, 15]
            - __class_fullname__: albumentations.augmentations.transforms.Blur
              blur_limit: [3, 15]
            - __class_fullname__: albumentations.augmentations.transforms.MotionBlur
              blur_limit: [5, 25]
            - __class_fullname__: albumentations.augmentations.transforms.MedianBlur
              blur_limit: [3, 15]
      - __class_fullname__: albumentations.augmentations.geometric.resize.RandomScale
        always_apply: False
        scale_limit: [0.05, 0.4]
        p: 1
      - __class_fullname__: albumentations.augmentations.transforms.GaussNoise
        always_apply: False
        mean: 0
        var_limit: [0.0, 25]
        per_channel: True
        p: 0.2
      - __class_fullname__: albumentations.augmentations.transforms.JpegCompression
        always_apply: False
        quality_lower: 10
        quality_upper: 75
        p: 0.7
      - __class_fullname__: albumentations.augmentations.geometric.resize.Resize
        always_apply: False
        height: 256
        width: 256
        p: 1
      - __class_fullname__: albumentations.augmentations.transforms.Normalize
        always_apply: false
        max_pixel_value: 255.0
        mean:
          - 0
          - 0
          - 0
        p: 1
        std:
          - 1
          - 1
          - 1

val_aug:
  transform:
    __class_fullname__: albumentations.core.composition.Compose
    bbox_params: null
    keypoint_params: null
    p: 1
    transforms:
      - __class_fullname__: albumentations.augmentations.transforms.LongestMaxSize
        always_apply: False
        max_size: 384
        p: 1
      - __class_fullname__: albumentations.augmentations.transforms.PadIfNeeded
        always_apply: False
        min_height: 384
        min_width: 384
        border_mode: 0 # cv2.BORDER_CONSTANT
        value: 0
        mask_value: 0
        p: 1
      - __class_fullname__: albumentations.augmentations.transforms.Normalize
        always_apply: false
        max_pixel_value: 255.0
        mean:
          - 0
          - 0
          - 0
        p: 1
        std:
          - 1
          - 1
          - 1

